# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
- stage: DevDeploy
- stage: QADeploy
- stage: ProdDeploy

steps:
- script: echo Job1, Step1
  displayName: 'Run a one-line script'

