# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

#Pipeline > Stages > Jobs > Tasks (Steps)
jobs:
- job: Job1
  steps:
  - script: echo job2 - Hello, changed!
    displayName: 'Run a one-line script - job 1'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: Job2
  dependsOn: Job1
  steps:
    - script: echo job2
      displayName: 'Run a one-line script - job 2'

- job: Job3
  dependsOn: Job2
  steps:
    - script: echo job3
      displayName: 'Run a one-line script - job 3'
