trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

#Pipeline > Stages > Jobs > Tasks (Steps)
stages:
- stage: Build
  jobs: 
  - job: Programas
  #programas preinstalados en las máquinas (da igual el so)
    steps:
      - bash: java -version
      - bash: node --version
      - bash: python --version
      - bash: mvn -version
      - bash: docker version




# #variable a nivel stage
#   variables:
#    environment: Build
#   jobs:
#   - job: Job1
#   #variable a nivel job
#     variables:
#      job: job1
#     steps:
#     - bash: echo Build 1 job1
#     - bash: echo variable pipeline $(Pipeline Level.Variable)
#     - bash: echo variable stage $(environment)
#     - bash: echo variable job $(job)
#       displayName: 'Build 1 job1'
#   - job: Job2
#     steps:
#     - script: |
#         echo Add other tasks to build, test, and deploy your project.
#       displayName: 'Build 1 job2'

#Ctrl + K + C Comment Block
#Ctrl + K + U Uncomment Block


# - stage: DevDeploy
#   dependsOn: Build
#   jobs:
#   - job: Job3
#   #eliminamos dependencia otro stage
#     #dependsOn: Job1
#     steps:
#       - script: echo Build 2 job3
#         displayName: 'Build 2 job3'
#   - job: Job4
#     dependsOn: Job3
#     steps:
#       - script: echo Build 2 job4
#         displayName: 'Build 2 job4'

# - stage: QADeploy
#   dependsOn: 
#   - Build
#   jobs:
#   - job: Job5
#   #eliminamos dependencia otro stage
#     #dependsOn: 
#     #- Job2
#     #- Job3
#     steps:
#       - script: echo Build 3 job5
#         displayName: 'Build 3 job5'

# - stage: ProdDeploy
#   dependsOn: 
#   - QADeploy
#   - DevDeploy
#   jobs:
#   - job: Job6
#     steps:
#       - script: echo Build 4 job6
#         displayName: 'Build 4 job6'