
trigger:
- master

resources:
- repo: self

#Stage1:
  #Build DOcker image

variables:
  tag: 23 
  #'$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub Millijf'
        repository: 'millanjf/test-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'


  #Publish k8s files
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'k8s'
        publishLocation: 'Container'


#Stage2:
#Deploy to k8s cluster


- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: ls -R $(System.ArtifactsDirectory)
      displayName: 'ArtifactsDirectory'
    
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'k8s'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
      
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'aks-k8s'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'millanjf/test-devops:$(tag)'
        

    

