trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

#Pipeline > Stages > Jobs > Tasks (Steps)
Stages:
- stage: Build
  jobs:
  - job: Job1
    steps:
    - bash: echo Build 1 job1
      displayName: 'Build 1 job1'
  - job: Job2
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
      displayName: 'Build 1 job2'

- stage: DevDeploy
  jobs:
  - job: Job3
  #eliminamos dependencia otro stage
    #dependsOn: Job1
    steps:
      - script: echo Build 2 job3
        displayName: 'Build 2 job3'
  - job: Job4
    dependsOn: Job3
    steps:
      - script: echo Build 2 job4
        displayName: 'Build 2 job4'

- stage: QADeploy
  jobs:
  - job: Job5
  #eliminamos dependencia otro stage
    #dependsOn: 
    #- Job2
    #- Job3
    steps:
      - script: echo Build 3 job5
        displayName: 'Build 3 job5'